# Generated by Django 2.0.3 on 2020-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200630_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.FloatField()),
                ('toppings', models.CharField(blank=True, max_length=40, null=True)),
                ('extras', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
