# Generated by Django 2.0.3 on 2020-07-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_item_incart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='incart',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
